Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -141,7 +141,9 @@ jobs:
       - shell: "bash"
         run: | # Check and warn
           set -ex
-          export SCCACHE_DIR="$(sccache --show-stats | grep "Cache location" | cut -d '"' -f2 | sed 's/\\\\/\\/g')" && echo "SCCACHE_DIR=$SCCACHE_DIR" >> $GITHUB_ENV
+          export SCCACHE_DIR="$(sccache --show-stats | grep "Cache location" | cut -d '"' -f2 | sed 's/\\\\/\\/g')"
+          export SCCACHE_DIR="$(echo "$SCCACHE_DIR" | sed -E 's#([A-Za-z]):#/\L\1#g; s#\\\\#/#g')"  # win -> posix
+          echo "SCCACHE_DIR=$SCCACHE_DIR" >> $GITHUB_ENV
           export SCCACHE_CACHE_SIZE=2G && echo "SCCACHE_CACHE_SIZE=$SCCACHE_CACHE_SIZE" >> $GITHUB_ENV  # Ignored??
           sccache --show-stats # Check location?
           sccache --zero-stats
@@ -171,7 +173,7 @@ jobs:
       - shell: "bash"
         run: | # Clean the cache by removing unaccessed files during this build.
           sccache --show-stats
-          find "$SCCACHE_DIR" -type f ! -anewer README.md -delete -print | wc -l
+          find "$SCCACHE_DIR" -type f ! -anewer README.md -delete -print | wc -l || echo "Find failed"
           sccache --show-stats
       # </Install and build>
       #
